---
name: maven build
on:
  push:
    branches:
      - main
    paths-ignore: ['paper/**', 'README.md', 'LICENSE.txt']
  pull_request:
    branches:
      - main
    paths-ignore: ['paper/**', 'README.md', 'LICENSE.txt']
jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
        java: [11, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
      - run: mvn clean install
